<a href="https://colab.research.google.com/github/likit/Advanced-community-health-course/blob/main/sqlite_database_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Accessing data using Python sqlite3 module.

In [ ]:
import sqlite3

Connect to the SQLite database and run a SQL command. To get a single result from the command, use **fetchone** method. The result will be a tuple of values.

In [ ]:
try:
  con = sqlite3.connect('hospital.db')
  cursor = con.cursor()
  print('Connected to the db successfully.')
  cursor.execute('SELECT count(*) FROM doctors;')
  total_doctors = cursor.fetchone()
  print(f'Total doctors is {total_doctors}')
  cursor.close()
except:
  print('Error while executing SQL command.')
finally:
  if con:
    con.close()
    print('SQLite connection has been closed.')

Connected to the db successfully.
Total doctors is (30,)
SQLite connection has been closed.

In [ ]:
try:
  con = sqlite3.connect('hospital.db')
  cursor = con.cursor()
  print('Connected to the db successfully.')
  cursor.execute('SELECT * FROM doctors;')
  a_doctor = cursor.fetchone()
  print(f'The first doctors is {a_doctor}')
  cursor.close()
except:
  print('Error while executing SQL command.')
finally:
  if con:
    con.close()
    print('SQLite connection has been closed.')

Connected to the db successfully.
The first doctors is (1, 'Larry', 'Patel', '0953979718', 'MED')
SQLite connection has been closed.

To query all rows from the database, use **fetchall** method, which returns a list of tuples.

In [ ]:
try:
  con = sqlite3.connect('hospital.db')
  cursor = con.cursor()
  print('Connected to the db successfully.')
  cursor.execute('SELECT * FROM doctors;')
  doctors = cursor.fetchall()
  print(f'The first doctors is {doctors}')
  cursor.close()
except:
  print('Error while executing SQL command.')
finally:
  if con:
    con.close()
    print('SQLite connection has been closed.')

Connected to the db successfully.
The first doctors is [(1, 'Larry', 'Patel', '0953979718', 'MED'), (2, 'Joshua', 'Holloway', '4226068794', 'ER'), (3, 'Tammy', 'Richardson', '7075041268', 'OTH'), (4, 'Amanda', 'Andersen', '3151389665', 'MED'), (5, 'Mary', 'Drake', '8084236287', 'GYN'), (6, 'Katherine', 'Harper', '0883872318', 'GYN'), (7, 'Amanda', 'Fernandez', '0278973052', 'GYN'), (8, 'Diana', 'Hansen', '5963878586', 'GYN'), (9, 'Jason', 'Thompson', '8963746696', 'MED'), (10, 'Nancy', 'Travis', '9973904570', 'ER'), (11, 'Anthony', 'Jones', '2536360252', 'OTH'), (12, 'Charles', 'Brooks', '8930232088', 'MED'), (13, 'Jill', 'Griffith', '7933902508', 'GYN'), (14, 'Miranda', 'Williams', '0679454629', 'ER'), (15, 'William', 'Baldwin', '1386596433', 'MED'), (16, 'Sonia', 'Simpson', '3382409681', 'ER'), (17, 'Noah', 'Mckay', '7570325919', 'ER'), (18, 'Sheri', 'Bowen', '8822518616', 'OTH'), (19, 'Catherine', 'Spencer', '1504145162', 'GYN'), (20, 'Walter', 'Singleton', '7436896000', 'ER'), (21, 'Walter', 'Knapp', '1752788001', 'GYN'), (22, 'Lauren', 'Allen', '5378343161', 'GYN'), (23, 'Ashley', 'Barr', '5098602198', 'GYN'), (24, 'Jane', 'Miller', '9335979001', 'ER'), (25, 'Juan', 'Rodriguez', '1862801256', 'OTH'), (26, 'Patricia', 'Martin', '6981233879', 'GYN'), (27, 'David', 'Myers', '4354922330', 'OTH'), (28, 'Christine', 'Garza', '0330412258', 'ER'), (29, 'Seth', 'Walton', '6911492236', 'GYN'), (30, 'Daniel', 'Guzman', '4221737937', 'GYN')]
SQLite connection has been closed.

**Exercise**: can you create a data frame for all the doctors in this hospital?

Or you can iterate over the **execute** method directly.

In [ ]:
try:
  con = sqlite3.connect('hospital.db')
  cursor = con.cursor()
  print('Connected to the db successfully.')
  for row in cursor.execute('SELECT * FROM doctors;'):
    print(row)
  cursor.close()
except:
  print('Error while executing SQL command.')
finally:
  if con:
    con.close()
    print('SQLite connection has been closed.')

Connected to the db successfully.
(1, 'Larry', 'Patel', '0953979718', 'MED')
(2, 'Joshua', 'Holloway', '4226068794', 'ER')
(3, 'Tammy', 'Richardson', '7075041268', 'OTH')
(4, 'Amanda', 'Andersen', '3151389665', 'MED')
(5, 'Mary', 'Drake', '8084236287', 'GYN')
(6, 'Katherine', 'Harper', '0883872318', 'GYN')
(7, 'Amanda', 'Fernandez', '0278973052', 'GYN')
(8, 'Diana', 'Hansen', '5963878586', 'GYN')
(9, 'Jason', 'Thompson', '8963746696', 'MED')
(10, 'Nancy', 'Travis', '9973904570', 'ER')
(11, 'Anthony', 'Jones', '2536360252', 'OTH')
(12, 'Charles', 'Brooks', '8930232088', 'MED')
(13, 'Jill', 'Griffith', '7933902508', 'GYN')
(14, 'Miranda', 'Williams', '0679454629', 'ER')
(15, 'William', 'Baldwin', '1386596433', 'MED')
(16, 'Sonia', 'Simpson', '3382409681', 'ER')
(17, 'Noah', 'Mckay', '7570325919', 'ER')
(18, 'Sheri', 'Bowen', '8822518616', 'OTH')
(19, 'Catherine', 'Spencer', '1504145162', 'GYN')
(20, 'Walter', 'Singleton', '7436896000', 'ER')
(21, 'Walter', 'Knapp', '1752788001', 'GYN')
(22, 'Lauren', 'Allen', '5378343161', 'GYN')
(23, 'Ashley', 'Barr', '5098602198', 'GYN')
(24, 'Jane', 'Miller', '9335979001', 'ER')
(25, 'Juan', 'Rodriguez', '1862801256', 'OTH')
(26, 'Patricia', 'Martin', '6981233879', 'GYN')
(27, 'David', 'Myers', '4354922330', 'OTH')
(28, 'Christine', 'Garza', '0330412258', 'ER')
(29, 'Seth', 'Walton', '6911492236', 'GYN')
(30, 'Daniel', 'Guzman', '4221737937', 'GYN')
SQLite connection has been closed.

##Accessing data using Pandas.

In [ ]:
import pandas as pd

In [ ]:
con = sqlite3.connect('hospital.db')

In [ ]:
doctors = pd.read_sql_query('SELECT * FROM doctors', con=con)

In [ ]:
doctors

    id  firstname    lastname     license department_code
0    1      Larry       Patel  0953979718             MED
1    2     Joshua    Holloway  4226068794              ER
2    3      Tammy  Richardson  7075041268             OTH
3    4     Amanda    Andersen  3151389665             MED
4    5       Mary       Drake  8084236287             GYN
5    6  Katherine      Harper  0883872318             GYN
6    7     Amanda   Fernandez  0278973052             GYN
7    8      Diana      Hansen  5963878586             GYN
8    9      Jason    Thompson  8963746696             MED
9   10      Nancy      Travis  9973904570              ER
10  11    Anthony       Jones  2536360252             OTH
11  12    Charles      Brooks  8930232088             MED
12  13       Jill    Griffith  7933902508             GYN
13  14    Miranda    Williams  0679454629              ER
14  15    William     Baldwin  1386596433             MED
15  16      Sonia     Simpson  3382409681              ER
16  17       Noah       Mckay  7570325919              ER
17  18      Sheri       Bowen  8822518616             OTH
18  19  Catherine     Spencer  1504145162             GYN
19  20     Walter   Singleton  7436896000              ER
20  21     Walter       Knapp  1752788001             GYN
21  22     Lauren       Allen  5378343161             GYN
22  23     Ashley        Barr  5098602198             GYN
23  24       Jane      Miller  9335979001              ER
24  25       Juan   Rodriguez  1862801256             OTH
25  26   Patricia      Martin  6981233879             GYN
26  27      David       Myers  4354922330             OTH
27  28  Christine       Garza  0330412258              ER
28  29       Seth      Walton  6911492236             GYN
29  30     Daniel      Guzman  4221737937             GYN

In [ ]:
query = '''
SELECT firstname, lastname, license, code, name FROM doctors
JOIN departments ON doctors.department_code=departments.code
ORDER BY code ASC;
'''

In [ ]:
df = pd.read_sql_query(query, con)

In [ ]:
df.head()

  firstname  lastname     license code       name
0    Joshua  Holloway  4226068794   ER  Emergency
1     Nancy    Travis  9973904570   ER  Emergency
2   Miranda  Williams  0679454629   ER  Emergency
3     Sonia   Simpson  3382409681   ER  Emergency
4      Noah     Mckay  7570325919   ER  Emergency

In [ ]:
df.groupby('code').count()[['firstname']]

      firstname
code
ER            8
GYN          12
MED           5
OTH           5

In [ ]:
query = '''
SELECT code, count(*) AS num_doctors FROM doctors
JOIN departments ON doctors.department_code=departments.code
GROUP BY code;
'''

In [ ]:
pd.read_sql_query(query, con=con).set_index('code')

      num_doctors
code
ER              8
GYN            12
MED             5
OTH             5